import { Language, LearningStep } from '../types';

export const sampleLanguages: Language[] = [
  {
    id: 'lang-js',
    name: 'JavaScript',
    description: 'Build interactive web apps and master frontend logic.',
    icon: '🟨',
    difficulty: 'beginner',
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'lang-python',
    name: 'Python',
    description: 'Learn automation, data analysis, and backend development.',
    icon: '🐍',
    difficulty: 'beginner',
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'lang-react',
    name: 'React',
    description: 'Create modern UI using components, hooks, and state.',
    icon: '⚛️',
    difficulty: 'intermediate',
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'lang-html',
    name: 'HTML',
    description: 'Learn the structure of web pages and semantic markup.',
    icon: '🌐',
    difficulty: 'beginner',
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'lang-php',
    name: 'PHP',
    description: 'Build server-side applications and handle form data with PHP.',
    icon: '🐘',
    difficulty: 'intermediate',
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'lang-typescript',
    name: 'TypeScript',
    description: 'Add strong typing to JavaScript for more robust applications.',
    icon: '🟦',
    difficulty: 'intermediate',
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'lang-cpp',
    name: 'C++',
    description: 'Learn low-level programming and performance with C++.',
    icon: '💻',
    difficulty: 'advanced',
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'lang-csharp',
    name: 'C#',
    description: 'Build games, desktop apps, and web services with C#.',
    icon: '🎮',
    difficulty: 'intermediate',
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'lang-rust',
    name: 'Rust',
    description: 'Write safe, fast systems code with Rust.',
    icon: '🦀',
    difficulty: 'advanced',
    createdAt: new Date(),
    userId: 'sample',
  },
];

export const sampleLearningSteps: LearningStep[] = [
  {
    id: 'step-js-1',
    languageId: 'lang-js',
    title: 'Understand JavaScript basics',
    description: 'Learn variables, data types, functions, and control flow.',
    resources: ['MDN JavaScript Guide', 'freeCodeCamp JS Course'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-js-2',
    languageId: 'lang-js',
    title: 'Work with the DOM',
    description: 'Practice selecting elements and handling events in the browser.',
    resources: ['JavaScript DOM tutorial', 'YouTube DOM project'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-js-3',
    languageId: 'lang-js',
    title: 'Build a small project',
    description: 'Create a todo list or quiz app to apply what you learned.',
    resources: ['Project-based tutorials', 'CodePen examples'],
    completed: false,
    order: 3,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-python-1',
    languageId: 'lang-python',
    title: 'Learn Python syntax',
    description: 'Practice variables, loops, functions, and lists.',
    resources: ['Python.org tutorial', 'Automate the Boring Stuff'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-python-2',
    languageId: 'lang-python',
    title: 'Build a simple script',
    description: 'Write a script to automate a daily task or parse text.',
    resources: ['Real Python projects', 'Python scripting examples'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-react-1',
    languageId: 'lang-react',
    title: 'Learn React components',
    description: 'Understand JSX, props, and component structure.',
    resources: ['React docs', 'Create React App tutorial'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-react-2',
    languageId: 'lang-react',
    title: 'Use hooks for state and effects',
    description: 'Practice useState, useEffect, and custom hooks.',
    resources: ['React hooks guide', 'Hook examples'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-html-1',
    languageId: 'lang-html',
    title: 'Learn HTML structure',
    description: 'Practice using headings, paragraphs, links, and images.',
    resources: ['HTML living standard', 'freeCodeCamp HTML course'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-html-2',
    languageId: 'lang-html',
    title: 'Use semantic HTML',
    description: 'Understand sections, articles, nav, and accessibility best practices.',
    resources: ['WebAIM accessibility guide', 'HTML semantics guide'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-html-3',
    languageId: 'lang-html',
    title: 'Build a simple web page',
    description: 'Create a personal profile page with structured HTML.',
    resources: ['HTML project ideas', 'Beginner web page examples'],
    completed: false,
    order: 3,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-php-1',
    languageId: 'lang-php',
    title: 'Learn PHP syntax',
    description: 'Practice variables, functions, and basic PHP scripts.',
    resources: ['PHP.net tutorial', 'PHP beginner guide'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-php-2',
    languageId: 'lang-php',
    title: 'Handle form data',
    description: 'Build a form and process input using PHP.',
    resources: ['PHP forms tutorial', 'Server-side form handling'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-php-3',
    languageId: 'lang-php',
    title: 'Connect to a database',
    description: 'Store and retrieve data with PHP and MySQL.',
    resources: ['PHP MySQL tutorial', 'PDO examples'],
    completed: false,
    order: 3,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-ts-1',
    languageId: 'lang-typescript',
    title: 'Learn TypeScript basics',
    description: 'Understand types, interfaces, and type safety.',
    resources: ['TypeScript docs', 'TypeScript beginner guide'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-ts-2',
    languageId: 'lang-typescript',
    title: 'Use TypeScript with JavaScript',
    description: 'Add types to functions and objects in a small app.',
    resources: ['TS with React tutorial', 'TypeScript examples'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-ts-3',
    languageId: 'lang-typescript',
    title: 'Build a typed project',
    description: 'Create a typed component or utility library with TypeScript.',
    resources: ['TypeScript project ideas', 'Advanced TS patterns'],
    completed: false,
    order: 3,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-cpp-1',
    languageId: 'lang-cpp',
    title: 'Learn C++ fundamentals',
    description: 'Practice variables, pointers, and control flow.',
    resources: ['C++ basics tutorial', 'LearnCpp.com'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-cpp-2',
    languageId: 'lang-cpp',
    title: 'Work with classes and objects',
    description: 'Build a simple class-based program in C++.',
    resources: ['C++ OOP guide', 'Object-oriented C++ examples'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-cpp-3',
    languageId: 'lang-cpp',
    title: 'Manage memory safely',
    description: 'Learn about stack vs heap, references, and smart pointers.',
    resources: ['C++ memory management', 'Smart pointers tutorial'],
    completed: false,
    order: 3,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-csharp-1',
    languageId: 'lang-csharp',
    title: 'Learn C# basics',
    description: 'Practice syntax, classes, and simple programs.',
    resources: ['Microsoft C# docs', 'C# beginner tutorials'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-csharp-2',
    languageId: 'lang-csharp',
    title: 'Build a C# console app',
    description: 'Create a command-line tool using C# and .NET.',
    resources: ['C# console app guide', 'dotnet tutorials'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-csharp-3',
    languageId: 'lang-csharp',
    title: 'Use LINQ and collections',
    description: 'Work with lists, arrays, and LINQ queries in C#.',
    resources: ['LINQ tutorial', 'C# collections guide'],
    completed: false,
    order: 3,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-rust-1',
    languageId: 'lang-rust',
    title: 'Learn Rust ownership',
    description: 'Understand ownership, borrowing, and lifetimes.',
    resources: ['The Rust Book', 'Rust ownership guide'],
    completed: false,
    order: 1,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-rust-2',
    languageId: 'lang-rust',
    title: 'Write Rust functions and structs',
    description: 'Practice functions, structs, and enums in Rust.',
    resources: ['Rust structs tutorial', 'Rust functions guide'],
    completed: false,
    order: 2,
    createdAt: new Date(),
    userId: 'sample',
  },
  {
    id: 'step-rust-3',
    languageId: 'lang-rust',
    title: 'Build a small Rust project',
    description: 'Create a CLI or small app using Cargo and Rust modules.',
    resources: ['Rust project ideas', 'Cargo tutorial'],
    completed: false,
    order: 3,
    createdAt: new Date(),
    userId: 'sample',
  },
];

export const getSampleStepsForLanguage = (languageId: string): LearningStep[] =>
  sampleLearningSteps.filter((step) => step.languageId === languageId);

export const createDefaultStepsForLanguage = (language: Language): LearningStep[] => {
  const name = language.name || 'this language';
  return [
    {
      id: `${language.id}-step-1`,
      languageId: language.id,
      title: `Learn ${name} basics`,
      description: `Understand the key concepts, syntax, and tools used in ${name}.`,
      resources: [`${name} documentation`, `${name} beginner tutorial`],
      completed: false,
      order: 1,
      createdAt: new Date(),
      userId: language.userId || 'sample',
    },
    {
      id: `${language.id}-step-2`,
      languageId: language.id,
      title: `Practice ${name} fundamentals`,
      description: `Build small exercises to reinforce what you learned in ${name}.`,
      resources: [`${name} practice problems`, `${name} example projects`],
      completed: false,
      order: 2,
      createdAt: new Date(),
      userId: language.userId || 'sample',
    },
    {
      id: `${language.id}-step-3`,
      languageId: language.id,
      title: `Create a beginner ${name} project`,
      description: `Apply your new skills by building a small ${name} project.`,
      resources: [`Beginner ${name} project ideas`, `${name} community tutorials`],
      completed: false,
      order: 3,
      createdAt: new Date(),
      userId: language.userId || 'sample',
    },
  ];
};
